export const data = [
  {
    title: "AMZN",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "TSLA",
    quantity: "200",
    ana: "-0.25 %",
    color: "green",
    risk: "High Risk",
  },
  {
    title: "ABQQ",
    quantity: "200",
    ana: "-0.25 %",
    color: "green",
    risk: "High Risk",
  },
  {
    title: "MSFT",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "PYPL",
    quantity: "200",
    ana: "-0.25 %",
    color: "green",
    risk: "Low Risk",
  },
  {
    title: "NFLX",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "NFLX",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "NFLX",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "NFLX",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "NFLX",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "NFLX",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "NFLX",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "NFLX",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "NFLX",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "NFLX",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "NFLX",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
  {
    title: "NFLX",
    quantity: "200",
    ana: "-0.25 %",
    color: "orange",
    risk: "Low Risk",
  },
];
